[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.8.2", features = ["i128", "prime", "zeroize"], default-features = false, package = "num-bigint-dig" }

